# --- START OF FILE HELIOS_EMBED/pyproject.toml ---
[build-system]
requires = ["setuptools>=61.0", "wheel", "torch", "pybind11"]
build-backend = "setuptools.build_meta"
# --- END OF FILE HELIOS_EMBED/pyproject.toml ---