[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "helios-embed"
version = "0.0.0"
description = "Helios Embed scaffold"
requires-python = ">=3.9"
